### ISSUE TITLE
i can't install the tool

### ISSUE THREAD

**Issue by medxpy** [tomnomnom/anew#11]
sudo go install github.com/tomnomnom/anew@latest
# internal/unsafeheader
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# internal/abi
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# internal/cpu
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# internal/goexperiment
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# runtime/internal/atomic
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# runtime/internal/sys
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# internal/race
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# sync/atomic
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# unicode
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# unicode/utf8
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# math/bits
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# internal/itoa
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# container/list
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# crypto/internal/subtle
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# crypto/subtle
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# unicode/utf16
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# internal/nettrace
compile: version "go1.17.2" does not match go tool version "go1.17.1"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.17.2" does not match go tool version "go1.17.1"
med@med:~$ go version
go version go1.17.1 linux/amd64

**Comment by 3ntr0phy** [comment]
install it using 
`go install -v github.com/tomnomnom/anew@latest`

**Comment by medxpy** [comment]
@3ntr0phy thank you, it worked.

**Comment by az7rb** [comment]
I have a problem after installing the performance
I used the command:
go install -v github.com/tomnomnom/anew@latest
It was installed successfully but not working!

┌──(root💀kali)-[/home/kali/Desktop]
└─# for url in $(cat test-url.txt);do http -b $url | grep 'Disallow' | awk -F ' ' '{print $2}' | cut -c 2- | anew test-words.txt;done
Command 'anew' not found, did you mean:
  command 'afew' from deb afew
  command 'new' from deb mmh
  command 'new' from deb nmh
  command 'znew' from deb gzip
Try: apt install <deb name>

---------
                                                                                                                                             
┌──(root💀kali)-[/home/kali/Desktop]
└─# go version                                                                                                                           2 ⨯
go version go1.17.2 linux/amd64
