### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by Chr1sto-sec** [tomnomnom/anew#15]
go install -v github.com/tomnomnom/anew@latest   No command output is displayed

**Comment by Chr1sto-sec** [comment]
Please help me solve this problem as soon as possible, thank you

**Comment by Chr1sto-sec** [comment]
by the way 
GOVERSION="go1.17.7"

**Comment by Yuhzha** [comment]
> 



> go install -v github.com/tomnomnom/anew@latest 没有命令显示输出
我也遇到了这个问题，请问你解决了吗

**Comment by Yuuu99** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by Yuuu99** [comment]
我已解决，没有回显就是下载完成的意思，文件存放在go/bin/路径下

**Comment by rikosoo** [comment]
Here I tried but I can't install too. And i didn't fint in go/bin

**Comment by tomnomnom** [comment]
The instructions in the README have now been updated to reflect the new way to install the tool, and a go.mod file has been added.

`go install -v github.com/tomnomnom/anew@latest` should work now assuming a correctly functioning Go install :)
