### ISSUE TITLE
how to fix it 

### ISSUE THREAD

**Issue by knowthetech** [tomnomnom/anew#5]
# github.com/tomnomnom/anew
go/src/github.com/tomnomnom/anew/main.go:44:3: non-bool lines[line] (type struct {}) used as if condition

**Comment by shubhack-repo** [comment]
Me too getting this error

**Comment by knowthetech** [comment]
as i can see it's an issue in code bcz issue exist just after the update

**Comment by tomnomnom** [comment]
This should be fixed now, sorry!
